name: Deploy demo

on:
  push:
    branches:
      - staging
      - main
      - master

jobs:
  deploy_qa:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p apps/demo && cd apps/demo
            
            if [ -d ".git" ]; then
              git stash
              git pull origin main
            else
              git clone -b main https://github.com/yonathanth/GymFrontend.git
            fi
            
            npm install --force
            npm run build

            pid=$(pm2 pid "demo frontend" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading application"
              pm2 reload "demo frontend"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "demo frontend" -- start
              pm2 startup
              pm2 save
            fi
